

name: Cache Node and NPM Dependencies
description: "This action allows to cache both Node and NPM dependencies based on the package-lock.json file.
input:
  node-version:
    description: "Node.js version to use"
    default: "20.x"
    required: true
  working-dir:
    required: false
    description: The working directory of the application
    default: "."
    required: false

runs:
  using: composite
  steps:
    - name: setup-nodejs version
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
    - name: Download cached dependencies
      id: cache
      uses: actions/cache@v3
      with:
        key: node-modules-${{ hashFiles('${{ inputs.working-dir }}/package-lock.json') }}
        path: ${{ inputs.working-dir }}/node_modules
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash
      working-directory: ${{ inputs.working-dir }}

