name: building blocks

on: push

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, World!"
      - name: timepass
        run: echo "time pass "
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Failed Step
        run: | 
          echo "Lets Fail"
          exit 0
      - name: say goodbye
        run: echo "Goodbye "
      



  
