name: 02 - Workflow Events

on: workflow_dispatch

    

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Event Name
              run: |
                echo "Event Name on which this was triggreed : ${{ github.event_name }}"
