name: 02 - Workflow Events

on: 
    push:

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Event Name
              run: |
                echo "Event Name : ${{ github.event_name }}"