name: 04 - Using Actions

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: CHckout Code 
              run: git checkout
            - name: Printing Folders
              run: ls -ld