name: 13-caching.yaml
on: 
    workflow_dispatch:
        inputs:
            use-cache:
                type: boolan
                default: true
                description: "Whether to execute cache step"

jobs: 
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
              working-directory: 04-using-actions/react-app
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: 20.x
            - name: Install dependencies
              run: npm ci  
            - name: Testing
              run: npm run test
            - name: Build
              run: npm run build
            - name: Deploying to nonprod
              run: echo "Deploying to nonprod"
            
        
              
