name: 14 - Working with Artifacts
on:
    workflow_dispatch:
env:
    build_artifact_key: app-${{ github.sha }}
    test_artifact_key: tests-${{ github.sha }}
jobs: 
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 04-using-actions/react-app
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
            - name: Download cached dependencies
              id: cache
              uses: actions/cache@v3
              with:
                path: 04-using-actions/react-app/node_modules
                key: deps-node-modules-${{ hashFiles('04-using-actions/react-app/package-lock.json') }}
            - name: Install Dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm ci
            - name: Unit Tests
              run: npm run test -- --coverage
            - name: upload tests results
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ env.test_artifact_key }}
                  path: 04-using-actions/react-app/coverage
            - name: Build Code
              run: npm run build
            - name: upload artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ env.build_artifact_key }}
                  path: 04-using-actions/react-app/build

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Download artifacts
              uses: actions/download-artifact@v4
              with:
                  name: app
                  path: build
            - name: Show folder structure
              run: ls -R
            - name: Deploy
              run: echo "Deploying..."
        
        
