name: 16 - Working with Environments

run-name: 16 - Working with Environments | env - ${{ github.event.inputs.target-env }}
on: 
    workflow_dispatch:
        inputs:
            target-env:
                type: environment
                default: staging
                description: "Which environment the workflow will target"
jobs:
    echo:
        runs-on: ubuntu-latest
        environment: ${{ github.event.inputs.target-env }}
        env: 
            my-env-value: ${{ vars.MY_ENV_VALUE }}
        steps:
            - name:  wcho vars
              run: echo "Environment is ${{ env.my-env-value }}"

