name: 16 - Working with Environments


on: 
    workflow_dispatch:
jobs:
    echo-staging:
        runs-on: ubuntu-latest
        environment: staging
        env: 
            my-env-value: ${{ vars.MY_ENV_VALUE }}
        steps:
            - name:  wcho vars
              run: echo "Environment is ${{ env.my-env-value }}"
        
    echo-production:
        runs-on: ubuntu-latest
        environment: prod
        env: 
            my-env-value: ${{ vars.MY_ENV_VALUE }}
        steps:
            - name:  wcho vars
              run: echo "Environment is ${{ env.my-env-value }}"
        
    

