name: 17 - 1 - Custom Actions - Composite

run-name: 17 - 1 - Custom Actions - Composite 
on:
    workflow_dispatch:
        inputs:
            target-env:
                type: choice
                options:
                    - dev
                    - staging
                    - prod
env: 
    working-directory: 17-custom-actions/react-app
jobs:
    build:
        runs-on: ubuntu-latest    
        defaults:
            run:
                working-directory: ${{ env.working-directory }}
        steps: 
            - uses: actions/checkout@v4
            - name: Run custom action
              uses: ./.github/actions/composite-cache-deps
              with:
                  node-version: 20.x
                  working-directory: ${{ env.working-directory }}
            - name: test
              run: npm run test
            - name: build
              run: npm run build
              