name: 17 - 3 - Custom Actions - Docker 1
on:
    workflow_dispatch:
        inputs:
            url:
                description: "URL to ping"
                type: string
                default: "https://github.com"
                required: true
jobs:
    ping-url:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Ping URL
              uses: ./.github/actions/docker-ping-url
              with:
                url: ${{ github.event.inputs.url }}
                max_trials: 5
                interval: 2

            